name: ootd_ai
description: A Flutter app for outfit of the day recommendations with smart history and laundry tracking.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Material Design
  cupertino_icons: ^1.0.2

  # Image picking from camera and gallery
  image_picker: ^1.0.0

  shared_preferences: ^2.5.3
  
  intl: ^0.20.2
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Uncomment and add your fonts here if needed
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: assets/fonts/CustomFont-Regular.ttf
  #       - asset: assets/fonts/CustomFont-Bold.ttf
  #         weight: 700